# Form implementation generated from reading ui file '/home/laurent/Documents/Python/Tests_Exemples/test_multi_process_pandas/src/test_multi_process_pandas/views/main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plot = PlotWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        self.plot.setSizePolicy(sizePolicy)
        self.plot.setObjectName("plot")
        self.verticalLayout.addWidget(self.plot)
        self.horizontalLayout_cb = QtWidgets.QHBoxLayout()
        self.horizontalLayout_cb.setObjectName("horizontalLayout_cb")
        self.cb_ch1 = QtWidgets.QCheckBox(parent=MainWindow)
        self.cb_ch1.setChecked(True)
        self.cb_ch1.setObjectName("cb_ch1")
        self.horizontalLayout_cb.addWidget(self.cb_ch1)
        self.cb_ch2 = QtWidgets.QCheckBox(parent=MainWindow)
        self.cb_ch2.setChecked(True)
        self.cb_ch2.setObjectName("cb_ch2")
        self.horizontalLayout_cb.addWidget(self.cb_ch2)
        self.cb_ch3 = QtWidgets.QCheckBox(parent=MainWindow)
        self.cb_ch3.setChecked(True)
        self.cb_ch3.setObjectName("cb_ch3")
        self.horizontalLayout_cb.addWidget(self.cb_ch3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_cb.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_cb)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_kill = QtWidgets.QPushButton(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/process-stop.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_kill.setIcon(icon)
        self.btn_kill.setObjectName("btn_kill")
        self.gridLayout.addWidget(self.btn_kill, 3, 0, 1, 1)
        self.btn_stop = QtWidgets.QPushButton(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/record/media-playback-stop-3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_stop.setIcon(icon1)
        self.btn_stop.setObjectName("btn_stop")
        self.gridLayout.addWidget(self.btn_stop, 2, 0, 1, 1)
        self.btn_start = QtWidgets.QPushButton(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/record/media-playback-start.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_start.setIcon(icon2)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 0, 0, 1, 1)
        self.btn_pause = QtWidgets.QPushButton(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/record/media-playback-pause.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_pause.setIcon(icon3)
        self.btn_pause.setObjectName("btn_pause")
        self.gridLayout.addWidget(self.btn_pause, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.log = QtWidgets.QTextEdit(parent=MainWindow)
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.verticalLayout.addWidget(self.log)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dynamic Channels + Legend"))
        self.cb_ch1.setText(_translate("MainWindow", "ch1"))
        self.cb_ch2.setText(_translate("MainWindow", "ch2"))
        self.cb_ch3.setText(_translate("MainWindow", "ch3"))
        self.btn_kill.setText(_translate("MainWindow", "Kill"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_pause.setText(_translate("MainWindow", "Pause"))
from pyqtgraph import PlotWidget
